### ISSUE TITLE
Missing collection types in generated file

### ISSUE THREAD

**Issue by Maxwell2022** [intercom/contentful-typescript-codegen#126]
I've noticed that all the collections are not generated, they should extends [`CollectionProp<T>`](https://github.com/contentful/contentful-management.js/blob/5c36cabd0fdd010a8a7f1a4f5e0a4a3998d758cb/lib/common-types.ts#L210) from `contentful-management`

**Comment by AndrejGajdos** [comment]
Yes, it would be great to support this :/

**Comment by anna-visarsoft** [comment]
Agree. This is a big issue.

**Comment by AndrejGajdos** [comment]
I ended up using graphql-codegen instead of this project.
