### ISSUE TITLE
Type import confusion: how should I import the types generated by this package?

### ISSUE THREAD

**Issue by davidhousedev** [intercom/contentful-typescript-codegen#16]
Thank you for publishing this, it's very helpful!

As a TypeScript novice, I am a little confused about the best way to import these types. The research I've done suggests that importing from `@types` packages is discouraged as TypeScript would prefer for the types to be imported _along_ with the JS itself.

However, since I'm using these types to add typing to the Contentful Graphql responses that my React components expect, I'm not actually importing any JavaScript. The only thing I need to import is the type, and the TypeScript linter complains about this....

When I try:
```tsx
import { ILinkFields } from '@types/generated/contentful'
```

The error I get is:

```
Cannot import type declaration files. Consider importing 'generated/contentful' instead of '@types/generated/contentful'.ts(6137)
```

I've written the generated types to my project root at `@types/generated/contentful` and configured my TypeScript compiler to view my project root as the `basePath`.

```json
{
  "compilerOptions": {
    "noEmit": true,
    "baseUrl": ".",
    "jsx": "react",
    "allowJs": true,
    "esModuleInterop": true
  },
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```

I'd really appreciate some guidance here!

**Comment by EricWVGG** [comment]
@davidhousedev I believe that the idea behind putting this file into an `@types` folder is for people who are using this to publish packages. I could be totally mistaken.

I changed my command in `package.json` to read `contentful-typescript-codegen --output src/contentfulGeneratedTypes.ts`, and now I can just…
```
import { ISomeFields } from '../contentfulGeneratedTypes'
```

**Comment by davidhousedev** [comment]
Thanks @EricWVGG ! Yes, I think you're right. I took the same approach and it's working great :)
