### ISSUE TITLE
output file, object error

### ISSUE THREAD

**Issue by EricWVGG** [intercom/contentful-typescript-codegen#19]
When I run the script as per your example, `yarn contentful-typescript-codegen --output @types/generated/contentful.d.ts`, I get the error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:1080:7)
    at /Users/wvgg/projects/prior/web/node_modules/contentful-typescript-codegen/dist/contentful-typescript-codegen.js:389:39
...
```

This also happens with `yarn contentful-typescript-codegen --output '@types/generated/contentful.d.ts'` or  `yarn contentful-typescript-codegen --output 'contentful.d.ts'`

Running the script with no arguments, `yarn contentful-typescript-codegen` seems to work perfectly, putting the file in `/@types/generated/contentful.d.ts`

Am I overlooking something?

**Comment by EricWVGG** [comment]
never mind, I figured it out –_–

I am unclear on how to import these types now, but I see there's another issue for that.

**Comment by AaronLayton** [comment]
@EricWVGG what was your solution, I am having the same issues on Windows

**Comment by EricWVGG** [comment]
This was unfortunately so long ago that I can't really remember, and regardless I think my solution would be outdated in favor of better options.

I was working on a project that used Contentful alongside Gatsby; Gatsby just released a new, integrated GraphQL codegen, so I would just opt to use that today.

**Comment by EricWVGG** [comment]
(note: the Gatsby solution works with any GraphQL data source, not just Contentful, so that nicely steps around any platform-specific issues… it "just works")

**Comment by CupCakeR** [comment]
> @EricWVGG what was your solution, I am having the same issues on Windows

In my case the issue was trying to load the env stuff (@next/env) using `loadEnvConfig()` with `process.env.PWD` as directory instead of `process.cwd()`.
