### ISSUE TITLE
Package is not compatible with latest contentful 7.14.2

### ISSUE THREAD

**Issue by cajoy** [intercom/contentful-typescript-codegen#26]
I am getting errors after upgrade contentful to 7.14.2 :

```
TS2322: Type 'IRoute[]' is not assignable to type 'Entry<IRouteFields>[]'.
```

**Comment by cajoy** [comment]
There is new field has been added. Which is missing in the model: 

```
    space: {
      sys: SpaceLink
    }
```

**Comment by stevenpetryk** [comment]
Ah, thanks for pointing out.

**Comment by cajoy** [comment]
Is there any ETA?

**Comment by stevenpetryk** [comment]
Today! 😄

**Comment by stevenpetryk** [comment]
Upon fixing this, I realized that our build is broken by https://github.com/contentful/contentful.js/pull/398. I'm going to hold off on making this change until that PR is merged so that we can set a good `peerDependency` constraint on `contentful`.

**Comment by stevenpetryk** [comment]
In fact, `space` was never meant to be required, so this problem may fix itself. But let's wait on 398 and see.

**Comment by stevenpetryk** [comment]
@cajoy you should be able to upgrade `contentful` to `7.14.3` to resolve this issue now. Closing this out and the PR.

**Comment by cajoy** [comment]
I am on "contentful": "^7.14.4",

And the issue still exists
