### ISSUE TITLE
export enums

### ISSUE THREAD

**Issue by cajoy** [intercom/contentful-typescript-codegen#31]
For large projects sometimes I need to use string values from fields. But it is not always type safe if I declare enums manually. 

So for example I have following generated model: 

```
export interface IReactComponentFields {
  /** _entryTitle */
  entryTitle?: string | undefined

  /** Component */
  component:
    | 'red'
    | 'blue'
    | 'orange'
}
```

But sometimes I need to get this fields as Enum for exhaustiveCheck or some other needs.

But I can't generate Enum out of generated model. I can create Object iwth properties. But exhaustive check doesn't work with object properties.

So I would suggest to generate code like that:

```
export enum IReactComponentEnumComponent {
  red = 'red',
  blue = 'blue',
  orange = 'orange'
}

export interface IReactComponentFields {
  /** _entryTitle */
  entryTitle?: string | undefined

  /** Component */
  component: IReactComponentEnumComponent
}
```

That would be awesome to have

**Comment by stevenpetryk** [comment]
If you have a content type named `blogPost` with an enum on the `status` field, then you can use `IBlogPostFields[‘status’]` to access the enum. It’s how you reference fields as types in TypeScript. 

Let me know if that doesn’t work for you!

**Comment by cajoy** [comment]
It partially fix the problem as I can get "type" but it still doesn't provide actual enum.

I will do more tests and will let you know if it works everywhere
