### ISSUE TITLE
Should prettier be a hard requirement?

### ISSUE THREAD

**Issue by ALibrada** [intercom/contentful-typescript-codegen#32]
Hello !

I have been trying your script and I have gotten an error saying that I needed to install prettier. Can you state that as a dependency or in the documentation?

I will probably do it afterwards if I get time. 

Thanks :)

**Comment by ALibrada** [comment]
I have seen, it is a peer dependency... Silly me

**Comment by mathieutu** [comment]
Actually maybe it shouldn't be? It's cool to format with prettier if we have it, but force us to install it just for the script is bit much, don't you think?

Thanks.

**Comment by lorenzogm** [comment]
This is an example why prettier shouldn't be required: https://github.com/valtech-ch/ring/runs/2858342339?check_suite_focus=true

I need to install prettier and delay the action more than minute

![image](https://user-images.githubusercontent.com/2147574/122865104-146f7980-d326-11eb-95ec-262bfb176a9c.png)

it would be nice to have a parameter to disable it. Do you accept a PR for it?
