### ISSUE TITLE
Add apostrophe support

### ISSUE THREAD

**Issue by lukethacoder** [intercom/contentful-typescript-codegen#34]
![image](https://user-images.githubusercontent.com/13529535/82168435-1b95ae00-9902-11ea-843e-41c38a25bfd4.png)

Ran into a small bump in the road attempting to pull when using apostrophes in Contentful schemas. 

Could we use backticks as opposed to apostrophes in auto generated `.d.ts` file? This would allow for apostrophes in the schema.

**Comment by Jaden-Giordano** [comment]
I made a PR on this, the problem with just using backticks here is that its based on the project's prettier. So it'll reformat to use either double quotes or single quotes. The solution I proposed should work with whatever prettier configuration a project is using.
