### ISSUE TITLE
Bug? Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by asbjornh** [intercom/contentful-typescript-codegen#37]
I'm just trying out this tool because it looks cool and we might need something like this. The script fails for me with `TypeError: Cannot read property 'find' of undefined at Object.renderSymbol`.  

This seems to be caused by the below line: https://github.com/intercom/contentful-typescript-codegen/blob/c6e2f547eb66846546baf3e093aea5f830a2596c/src/renderers/contentful/fields/renderSymbol.ts#L6

`field.validations` can be `undefined` (I don't know how, but in our space this occurs). It might be the case that the Contentful `Field` type incorrectly asserts that `field.validations` always exists. Anyway I was able to get it running locally by editing the javascript for that line to be `(field.validations || []).find`.

**Comment by asbjornh** [comment]
I just discovered that the README specifies that the Content Management API should be used. We're using the Delivery API which probably explains the inconsistency.

Seeing as the above mentioned fix is relatively simple, I hope it can be included in order to also support the Delivery API. I'd be happy to submit a PR!

**Comment by stevenpetryk** [comment]
Sadly the Content Delivery API doesn't provide the relevant data to get full typing because it only gives you limited insight into entry validations.

**Comment by asbjornh** [comment]
While that's true, the types generated without validations are still very useful!

We're running the Contentful SDK in CI, so the Management API is not an option since it requires personal tokens which we don't want to have lying around in shared CI systems.

**Comment by stevenpetryk** [comment]
Ah, I see—the way we solve that is by having a service account in Contentful that has read-only access. We use its personal access token. Would that solve the problem for you? I'm pretty hesitant to support both Contentful APIs :)

**Comment by asbjornh** [comment]
Ok! I'm gonna close this then :)
