### ISSUE TITLE
add 'sys' or 'id' to generated types

### ISSUE THREAD

**Issue by lukethacoder** [intercom/contentful-typescript-codegen#5]
Adding 'sys' to the generated typings (as its something returned in the response) would be useful , mainly to retrieving the 'id' of the entry.

Getting the content type, when targeting multiple content types, (Similar to #4) would be very useful too. Ideally we wouldn't have to extend the generated typings to achieve this.

**Comment by stevenpetryk** [comment]
True! Thanks for the recommendation. I'll get #4 merged tomorrow.

**Comment by stevenpetryk** [comment]
Actually, got it merged tonight. Released as `2.0.0`. Enjoy!
